.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RELAX\-PROFILE" "7" "May 2018" "" ""
.
.SH "NAME"
\fBrelax\-profile\fR \- relax profile module
.
.SH "SYNOPSIS"
\fBrelax profile\fR \fIcommands\fR \.\.\.
.
.SH "DESCRIPTION"
The relax profile module has utility commands to manage your provisioning profiles from CLI\.
.
.SH "COMMAND"
.
.TP
\fBadd\fR
Add a provisioning profile\.
.
.TP
\fBfind\fR
Find provisioning profiles whose name matches a keyword\.
.
.TP
\fBls\fR
List provisioning profiles\.
.
.TP
\fBrm\fR
Remove provisioning profiles whose name matches a keyword\.
.
.SH "COPYRIGHT"
Relax is Copyright (C) 2017\-present, Shin Yamamoto \fIhttp://scenee\.com/\fR
.
.SH "SEE ALSO"
relax(1), relax\-keychain(7)
