#!/usr/bin/env bash -eu
# @(#) relax: `profile-rm` command

usage () {
	cat <<-EOM
	usage: ${ME} profile rm <provisioning-profile-name>

	EOM
	fin
}

# rm_provisioning_profile <provisioning-profile>
rm_provisioning_profile () {
	find_mobileprovision "$1" | \
	while IFS= read mobileprovision || [ -n $mobileprovision ]
	do
		if [[ ! -f "$mobileprovision" ]]; then
			fin "'$1' mobileprovision doesn't exist"
		fi
		rm -f "$mobileprovision"
		logi "Removed '$1':$mobileprovision"
	done
}

[[ $# != 0 ]] || usage

case $1 in
-h)
	usage
	;;
esac

rm_provisioning_profile "$@"
