#!/bin/bash -eu

usage () {
	cat <<-EOM
	Usage: ${ME} profile <command> ...

	Commands:
	    add		Add a provisioning profile
	    find	Find provisioning profiles
	    ls		List provisioning profiles
	    rm		Remove a provisioning profile
	EOM
	fin
}


if [ $# = 0 ]; then
	usage
fi

command=$1
shift
case $command in 
help)
	if [ $# == 0 ]
	then
		usage
	else 
		command=$1
		shift
		command_path="$(command -v "relax-$command" || true)"
		if ! [ -n "$command_path" ]; then
			die "No such command \`$command'"
		fi

		bash -f "$command_path" -h
		fin
	fi
	;;
"")
	usage
	fin
	;;
* )
	module_path=${0%/*}
	module=${module_path##*/}
	command_path="$(command -v "${module}-${command}" || true)"
	if ! [ -n "$command_path" ]; then
		die "No such $module command \`$command'"
	fi
	
	TRAP "clean_temp;"
	make_temp

	"$command_path" "$@"
	;;	
esac
