#!/usr/bin/env bash -eu
# @(#) relax: `profile-find` command
# completions

usage () {
	cat <<-EOM
	Usage: ${ME} profile find [-v] [--team <teamid>] [--latest] <provisioning-profile-name>

	Options:
	    -v			Verbose mode
	    --team <team>	Print mobileprovision files for a team.
	    --latest		Print the latest one if there are mobileprovision files with the same name.
	EOM
	fin
}

[[ $# != 0 ]] || usage

case $1 in
-h|--help) 
	usage 
	;;
--completions)
	echo "--team --latest"
	fin
	;;
esac

# `find_mobileprovision()` is defined in `libexec/util-build`
if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_VERBOSE".* ]]; then
	find_mobileprovision -v "$@"
else
	find_mobileprovision "$@"
fi
