#!/bin/bash

if [[ $NOCOLOR == true ]]; then

export NC=""
export BLACK=""
export RED=""
export GREEN=""
export YELLOW=""
export BLUE=""
export PURPLE=""
export CYAN=""
export WHITE=""
export BOLD=""

else

export  NC='\033[0m'       # Reset Color

# Regular Colors
export BLACK='\033[0;30m'        # Black
export RED='\033[0;31m'          # Red
export GREEN='\033[0;32m'        # Green
export YELLOW='\033[0;33m'       # Yellow
export BLUE='\033[0;34m'         # Blue
export PURPLE='\033[0;35m'       # Purple
export CYAN='\033[0;36m'         # Cyan
export WHITE='\033[0;37m'        # White
export BOLD='\033[1m'            # Black


fi
