#!/usr/bin/env bash -eu
# @(#) relax: constants

export REL_CONFIG="Relfile"
export REL_RELEASE_ROOT="Releases"
export REL_DATA_DIR=".relax"
export REL_TEMP_ROOT="$( [[ ${TMPDIR:-undefined} != undefined ]] && echo "$TMPDIR/$ME" || echo "/tmp/$ME" )"
export REL_CACHE_DIR="~/Library/Caches/Relax"

# TODO Rename this with 'REL_BAK_EXT'
export BAK_EXT="bak.relax"
