#!/usr/bin/env bash -eu
# @(#) relax: `package` command
# completions

usage() {
	cat <<-EOM
	usage: ${ME} package <release> <package_path>
	EOM
	fin
}

make_package() {
	if test $# != 2; then
		usage
	fi

	local release=$1
	local package_dir=$2

	[[ " ${REL_RELEASES[@]} " =~ " $release "  ]]  || die "Not found '$release' release"

	### Make artifacts

	logi "$ARROW Clean up $package_dir"

	rm -rf "$package_dir" > /dev/null 2>&1
	mkdir -p "$package_dir" > /dev/null 2>&1

	cp "$(relax-show $release ipa)" "$package_dir"

	archive="$(relax-show $release archive)"
	zipname="$(basename "$archive")".zip

	logi "$ARROW Install ipa and xcarchive"
	logi "Package Directory: $HERE/$package_dir"

	ditto -c -k --sequesterRsrc --keepParent "$archive" "$package_dir/$zipname"

	ls "$package_dir"
}


[[ $# != 0 ]] || usage

arg=$1
shift
case $arg in
-h|--help) 
	usage 
	;;
--completions)
	if [[ $# == 0 ]]; then
		echo "${REL_RELEASES[@]}"
	else
		:
	fi
	fin
	;;
*)
	;;
esac

make_package "$arg" "$@"
