#!/usr/bin/env bash -eu
# @(#) relax: `enc` command

usage () {
	cat <<-EOM
	usage: ${ME} enc [-p <password>] <file>

	EOM
	fin
}

# enc_file [-k <password>] <file>
enc_file() {
	local key src
	while [ $# != 0 ];
	do
		arg=$1
		shift
		case $arg in
		-p)
			[[ $# != 0 ]] || usage
			key=$1
			shift
			;;
		*)
			src=$arg
			;;
		esac
	done

	[[ -n $src ]] || usage;

	[[ -n $key ]] || key=$(openssl rand -base64 32 | head -c 16)

	local dst="$src".enc

	/usr/bin/openssl aes-256-cbc -k "$key" -in "$src" -out "$dst" -p -a > >(logv)
	if [[ $? = 0 ]]; then
		logi "Encrypted: $dst"
		logi "password: $key"
	else
		die
	fi

}

[[ $# != 0 ]] || usage

case $1 in
-h) usage ;;
esac

enc_file "$@"
