#!/usr/bin/env bash -eu
# Summary: List all available commands

set -e

usage () {
	cat <<-EOM
	usage: ${ME} commands

	EOM
	fin
}

print_modules () {
	echo "keychain"
	echo "profile"
}

IFS=: paths=($PATH)
shopt -s nullglob

if [[ $# = 0 ]]; then
	print_commands relax
	print_modules
else
	case $1 in
	-h)
		usage
		;;
	--modules)
		print_modules
		;;
	esac
fi
