#!/bin/bash -eu
# Summary: Apply a Relfile customization into your project

usage () {
	cat <<-EOM
	Usage: ${ME} apply <distribution>
	
	Apply your Info.plist and Build settings for a distribution in Relfile into your project.
	EOM
	fin
}

teardown_build_dry() {
	__kill_bg_xcodebuid_task

	set +u
	if [[ -d "$SRCROOT" ]]; then
		while IFS= read bak
		do
			rm "$bak"
		done < <(find "$SRCROOT" -name "*.$REL_BAK_EXT")
	fi
	set -u
}

Distribution=

while [[ $# != 0 ]]; do
	arg=$1
	shift
	case $arg in
	-h)
		usage
		;;
	*)
		Distribution="$arg"
		;;
	esac
done

[[ -n "$Distribution" ]] || usage


trap 'teardown_build_dry;' EXIT INT TERM
setup_build $Distribution
