#!/usr/bin/env bash -eu
# @(#) relax: `add` command

usage () {
	cat <<-EOM
	usage: ${ME} add <provisioning-profile>

	EOM
	fin
}

# add_provisioning_profile [-f]  <provisioning-profile>
add_provisioning_profile () {
	local provisioning_file="$1"

	if ! [ -z $provisioning_file ] && ! [ -f $provisioning_file ]; then
		die "Not found $provisioning_file "
	fi

	local temp_provisioning_plist="$REL_TEMP_DIR/provisioning.plist"

	decode_mobileprovision "$provisioning_file" "$temp_provisioning_plist"

	provisioning_uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" $temp_provisioning_plist)
	provisioning_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $temp_provisioning_plist)

	mkdir -p "$PROVISIONING_DST_DIR"
	local stored_provisionig_file="$PROVISIONING_DST_DIR/$provisioning_uuid.mobileprovision" 
	if [ -f "$stored_provisionig_file" ]; then
		logi "Already existing: $provisioning_name($provisioning_uuid)"
		fin
	fi

	logi "$ARROW Installing Provisioning profile: $provisioning_file"
	cp "$provisioning_file" "$stored_provisionig_file"
	logi "Added: $stored_provisionig_file"
}

[[ $# != 0 ]] || usage

case $1 in
-h) usage ;;
esac

if [[ -f "$1" ]]; then
	if grep -q "Provisioning Profile" "$1"; then
		add_provisioning_profile "$@"
	else
		usage
	fi
fi

if test $? = 0; then
	logi "${GREEN}Success${NC}"
fi
