#!/usr/bin/env bash -eu
# @(#) relax: `dec` command

usage () {
	cat <<-EOM
	usage: ${ME} dec -p <password> <file>

	EOM
	fin
}

# dec_file <file>
dec_file () {
	local password src
	while [ $# -ne 0 ];
	do
		arg=$1
		shift
		case $arg in
		-p)
			[[ $# != 0 ]] || usage
			password="$1"
			shift
			;;
		*)
			src=$arg
			;;
		esac
	done

	[[ -n $src ]] || usage;

	local dst="${src%.enc}"
	logi "$ARROW Decrypting $src"

	/usr/bin/openssl aes-256-cbc -k "$password" -in "$src" -out "$dst" -p -d -a > >(logv)
	if [[ $? = 0 ]]; then
		logi "Decrypted: $dst"
	else
		die
	fi
}

[[ $# != 0 ]] || usage

case $1 in
-h) usage ;;
esac

dec_file "$@"
