#!/usr/bin/env bash -eu
# @(#) relax: `rm` command

usage () {
	cat <<-EOM
	usage: ${ME} rm <provisioning-profile-name>

	EOM
	fin
}

# rm_provisioning_profile <provisioning-profile>
rm_provisioning_profile () {
	local mobileprovision="$(find_mobileprovision "$1")"
	if [[ ! -f "$mobileprovision" ]]; then
		fin "'$1' mobileprovision doesn't exist"
	fi
	rm -f "$mobileprovision"
	logi "Removed '$1':$mobileprovision"
}

if test $# = 0; then
	usage
fi

case $1 in
-h)
	usage
	;;
esac

rm_provisioning_profile "$@"

if test $? = 0; then
	logi "${GREEN}Success${NC}"
fi
