#!/bin/bash -eu
# @(#) relax: `show` command
# completions

usage() {
	cat <<-EOM
	usage: ${ME} show <distribution> <arg>

	Print the artifacts for a distribution

	Arg:
	    build:	Print the artifact directory
	    archive:	Print the xcarchive file
	    ipa:	Print the IPA file
	EOM
	fin
}

# show <release> <type>
show () {
	local release=$1
	local type=$2

	local data_root=$REL_RELEASE_ROOT/$release

	local path=""
	case $type in
	ipa)
		path="$(readlink $data_root/heads/ipa)"
		;;
	build)
		path=$data_root
		;;
	archive)
		path="$(readlink $data_root/heads/archive)"
		;;
	esac

	if [[ -n "$path" ]]; then
		echo "$path"
	fi
}
[[ $# != 0 ]] || usage

arg=$1
shift
case $arg in
-h|--help)
	usage
	;;
--completions)
	if [[ $# == 0 ]]; then
		echo "${REL_DISTRIBUTIONS[@]}"
	else
		if [[ " ${REL_DISTRIBUTIONS[@]} " =~ " $1 " ]]; then
			echo "build archive ipa"
		fi
	fi
	fin
	;;
*)
	distribution=$arg

	[[ " ${REL_DISTRIBUTIONS[@]} " =~ " $distribution "  ]]  || die "Not found '$distribution' distribution"

	[[ $# == 1 ]] || usage

	show "$distribution" "$1"
	;;
esac
