#!/bin/bash -eu
# @(#) relax: `symbolicate` command

usage () {
	cat <<-EOM
	usage: ${ME} symbolicate <crashlog> <archive|ipa>

	If you use an IPA file, a crash log can't be fullly symbolicated.
	EOM
	fin
}


check_binary_image () {
	local app_name="${1##*/}"
	local crashlog="$2"

	local product_name=
	if [[ "$app_name" =~ (.*)\.app  ]]; then
		product_name="${BASH_REMATCH[1]}";
	fi

	local result=false
	xcrun dwarfdump --uuid "$app_path/$product_name" \
	| tr '[:upper:]' '[:lower:]' | tr -d '-' \
	| awk '{ print $2 }' \
	| while IFS= read -r uuid && [[ -n $uuid ]]
	do
		if grep -q $uuid "$crashlog"; then
			result=true
		fi
	done

	if [[ $result == false ]]; then
		logi "$WARN Not found a binary image for the crash log: $app_path/$product_name"
	fi
}

# symbolicate <crashlog> <material>
symbolicate () {
	local crashlog material out
	[ $# -eq 2 ] || usage

	crashlog=$1
	material=$2

	[[ -d /Applications/Xcode.app ]] || die "Please install Xcode.app"
	
	export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer

	symbolicatecrash_path=/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/Resources/symbolicatecrash
	
	local app_path dsym_path
	if grep -q "\.ipa$" <<< "$material"; then
		local payload=$REL_TEMP_DIR
		unzip -q "$material" -d "$payload"
		app_path=$(find "$payload" -name "*.app")
	elif grep -q "\.xcarchive$" <<< "$material"; then
		app_path=$(find "$material" -name "*.app")
		dsym_path=$(find "$material" -name "*.app.dSYM")
	else
		die "Unexpected file: $material"
	fi

	logi "$ARROW Symbolicating '$crashlog'..."
	logi "Log: symbolicate.log"

	check_binary_image $app_path $crashlog
	out=${crashlog%%\.crash}-symbolicated.crash
	logv "Using $app_path"
	if [[ -d "$dsym_path" ]]; then
		logv "Using $dsym_path"
	fi
	if "$symbolicatecrash_path" -v "$crashlog" "$app_path" "$dsym_path" -o "$out" 2>symbolicate.log; then
		logi "$ARROW $out"
	else
		die
	fi
}

[[ $# != 0 ]] || usage

case $1 in
-h) usage ;;
esac

symbolicate "$@"
