#!/usr/bin/env bash
# Usage: relax completions <command> [arg1 arg2...]
# completions

set -e

COMMAND="$1"

[[ -n "$COMMAND" ]] || fin

case $1 in
	releases)
		echo "${REL_RELEASES[@]}"
		;;
	--complete)
		exec relax-commands
		;;
	*)
		COMMAND_PATH="$(command -v "relax-$COMMAND")"
		if grep -iE "^# completions" "$COMMAND_PATH" >/dev/null; then
			shift
			exec "$COMMAND_PATH" --complete "$@"
		fi
		;;
esac
