#!/usr/bin/env bash -eu
# @(#) relax: `hash` command

usage () {
	cat <<-EOM
	Usage: ${ME} hash <ipa> [-F]

	Print a sha256 hash for an ipa file

	Options:
	    -F	Print a full hash
	EOM
	fin
}

# hash_file <file>
hash_file() {
	local is_full=false
	local ipa
	while [[ $# != 0 ]];
	do
		arg=$1
		shift
		case $arg in
		-F) 
			is_full=true 
			;;
		*) 
			ipa=$arg
			;;
		esac
	done

	[[ -f "$ipa" ]] || die "Not found $ipa"

	local hash_full=$(openssl dgst -sha256 "$ipa"  | awk -F= '{ gsub(" ","",$2); print $2; }')

	if [[ $is_full = true ]]; then
		echo $hash_full
	else
		echo ${hash_full:0:8}
	fi
}

 
[[ $# != 0 ]] || usage

case $1 in
-h) usage ;;
esac

hash_file "$@"
