#!/bin/bash
# Summary: Display the version of relax
#
# Displays the version number of this relax release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e

git_revision=""

if cd "${BASH_SOURCE%/*}" 2>/dev/null && git remote -v 2>/dev/null | grep -q relax; then
	git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
	git_revision="${git_revision#v}"
fi

echo "relax ${git_revision:-$REL_VERSION}"
