#!/usr/bin/env bash -eu
# Summary: List installed provisioning profiles

usage () {
	cat <<-EOM
	Usage: ${ME} ls-profiles

	List installed provisioning profiles

	EOM
}

ls_mobileprovision () {
	local mp_temp mp_file mp_name mp_team mp_team_id
	find "$PROVISIONING_DST_DIR" -name "*.mobileprovision" |\
	while IFS= read -r file; do
		mp_file=${file##*/}
		mp_temp="$REL_TEMP_DIR/${mp_file}"
		security cms -D -i "$file" > $mp_temp
		mp_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $mp_temp)
		mp_team=$(/usr/libexec/PlistBuddy -c "Print :TeamName" $mp_temp)
		mp_team_id=$(/usr/libexec/PlistBuddy -c "Print :TeamIdentifier:0" $mp_temp)
		logi "$mp_name [${mp_team}($mp_team_id)]"
		logv "	${file}"
	done
}

while [[ $# != 0 ]]; do
	arg=$1
	shift
	case $arg in
	-h)
		usage
		fin
		;;
	esac
done

ls_mobileprovision
