#!/usr/bin/env bash -eu
# Summary: List installed provisioning profiles

usage () {
	cat <<-EOM
	Usage: ${ME} ls-profiles

	List provisioning profiles

	EOM
	fin
}

while [[ $# != 0 ]]; do
	arg=$1
	shift
	case $arg in
	-h)
		usage
		;;
	esac
done

find_mobileprovision -v
