#!/usr/bin/env bash -eu
# Summary: List all available commands


set -e

IFS=: paths=($PATH)

shopt -s nullglob

if [[ $# = 0 ]]; then
	{ 
	for path in "${paths[@]}"; do
		for command in "$path/relax-"*; do
			command="${command##*relax-}"
			echo $command
		done
	done
	echo "help"
	} | grep -v "completions" | sort -u
elif [[ $1 = "--modules" ]]; then
	echo "keychain"
fi
