#!/bin/bash -eu
# @(#) relax: `init` command

usage () {
	cat <<-EOM
	usage: ${ME} init
	EOM
	fin
}

print_completion_path () {
	completion="$SOURCE_PATH/completions/relax.${SHELL##*/}"
	echo "$completion"
}

Scheme=

while [ $# -ne 0 ];
do
	arg=$1
	shift
	case $arg in
	completion|completions)
		print_completion_path
		fin
		;;
	-h|--help|*)
		usage
		;;
	esac
done

if ! test -f $PWD/$REL_CONFIG; then
	# Set up Scheme
	## Get scheme list
	xcodebuild -list > $REL_TEMP_DIR/xcode-build-list

	cat $REL_TEMP_DIR/xcode-build-list | grep -q 'This project contains no schemes.' && die "Please set up a shared scheme"

	awk -f $LIBEXEC_DIR/init-scheme.awk $REL_TEMP_DIR/xcode-build-list \
		> $REL_TEMP_DIR/xcode-build-schemes
	source $REL_TEMP_DIR/xcode-build-schemes

	## Generate Relfile configuration
	Scheme="${xcode_schemes[0]}"

	logi "$ARROW Creating Relfile"
	generate_relfile "$Scheme" ""
	cp $REL_TEMP_DIR/Relfile ./Relfile
	logi "Done"
else
	fin "Found an existing Relfile"
fi
