#!/bin/bash -eu
# Summary: Create a IPA file

usage () {
	cat <<-EOM
	Usage: ${ME} dist --scheme <Scheme> --profile <Profile>
	
	--scheme,-s	A scheme name
	--profile,-p	A provisioning profile name

	EOM
	fin
}

Distribution=
Scheme=
Profile=

while [[ $# != 0 ]]; do
	arg=$1
	shift
	case $arg in
	--scheme|-s)
		Scheme="$1"
		shift
		;;
	--profile|-p)
		Profile="$1"
		shift
		;;
	*)
		Distribution="$arg"
		;;
	esac
done


if [[ -n "$Scheme" && -n "$Profile" ]]; then
	generate_relfile "$Scheme" "$Profile"
	REL_CONFIG_PATH="$REL_TEMP_DIR/Relfile"
	Distribution=adhoc
	REL_DISTRIBUTIONS="$Distribution"
else
	if [[ -n "$Scheme" || -n "$Profile" ]]; then
		usage
	fi
fi

[[ -n "$Distribution" ]] || usage

relax-archive "$Distribution"
relax-export "$Distribution"
