#!/usr/bin/env bash -eu
# @(#) relax: `show` command
# completions

usage() {
	cat <<-EOM
	usage: ${ME} show <release> <item>

	Print the latest artifacts

	Items:
	    build:	Print the latest build directory
	    archive:	Open the latest archive file
	    ipa:	Print the latest IPA 
	EOM
	fin
}

[[ $# != 0 ]] || usage

arg=$1
shift
case $arg in
-h|--help)
	usage
	;;
--completions)
	if [[ $# == 0 ]]; then
		echo "${REL_RELEASES[@]}"
	else
		if [[ " ${REL_RELEASES[@]} " =~ " $1 " ]]; then
			echo "build archive ipa"
		fi
	fi
	fin
	;;
*)
	release=$arg

	[[ " ${REL_RELEASES[@]} " =~ " $release "  ]]  || die "Not found '$release' release"

	[[ $# == 1 ]] || usage
	if ! read_path "$release" "$1"; then
		die "Not found the latest $1"
	fi
	;;
esac
