#!/usr/bin/env bash -eu
# @(#) relax: `add` command

usage_add () {
	cat <<-EOM
	usage: ${ME} add <provisioning-profile>
	       ${ME} add -P <password> <p12>

	EOM
}

# add_identities  -P <password> <p12>
add_identities () {
	local password=
	while [ $# -ne 1 ];
	do
		if [ $# = 0 ]; then
			usage_add
			fin
		fi

		arg=$1
		shift
		case $arg in
		-P)
			password=$1
			shift
			;;
		esac
	done
	
	if ! is_exist_keychain $REL_KEYCHAIN; then
		logi "$ARROW Creating relax.keychain"
		create_relax_keychain
	fi


	logi "$ARROW Importing PKCS12: $1"
	import_p12_into_keychain -k $REL_KEYCHAIN_PASSWD -P $password $1 $REL_KEYCHAIN

	init_keychain -k $REL_KEYCHAIN_PASSWD $REL_KEYCHAIN 
	logi "Default keychain: $($SECURITY default-keychain | xargs)"

	logi "$ARROW Validating imported certificates..."
	validate_certs -P $password $1
}

# add_provisioning_profile [-f]  <provisioning-profile>
add_provisioning_profile () {
	local provisioning_file="$1"

	if ! [ -z $provisioning_file ] && ! [ -f $provisioning_file ]; then
		die "Not found $provisioning_file "
	fi

	local temp_provisioning_plist="$REL_TEMP_DIR/provisioning.plist"

	decode_mobileprovision "$provisioning_file" "$temp_provisioning_plist"

	provisioning_uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" $temp_provisioning_plist)
	provisioning_name=$(/usr/libexec/PlistBuddy -c "Print :Name" $temp_provisioning_plist)

	mkdir -p "$PROVISIONING_DST_DIR"
	local stored_provisionig_file="$PROVISIONING_DST_DIR/$provisioning_uuid.mobileprovision" 
	if [ -f "$stored_provisionig_file" ]; then
		logi "Already existing"
		fin
	fi

	logi "$ARROW Installing Provisioning profile: $provisioning_file"
	cp "$provisioning_file" "$stored_provisionig_file"
	logi "Added: $stored_provisionig_file"
}

if test $# = 0; then
	usage_add
	fin
fi

case $1 in
-h)
	usage_add
	fin
	;;
esac

if [[ -f "$1" ]]; then
	if grep -q "Provisioning Profile" "$1"; then
		add_provisioning_profile "$@"
	else
		usage_add
		fin
	fi
elif [[ $1 == "-P" ]]; then
	add_identities "$@"
else
	die "Not Found $1"
fi

if test $? = 0; then
	logi "${GREEN}Success${NC}"
fi
