#!/usr/bin/env bash -eu
# @(#) relax: utility functions

#################
###  Defines  ###
#################

export REL_TEMP_DIR=
export REL_LOG_LEVEL=
export REL_LOG_LEVEL_DEBUG=DEBUG
export REL_LOG_LEVEL_VERBOSE=VERBOSE
export ARROW="${BLUE}==>${NC}${BOLD}"
export ERR=${RED}Error:${NC}
export WARN=${YELLOW}Warning:${NC}
export NOTE=${BOLD}Note:${NC}

#################
### Functions ###
#################

# print_completions <module>
print_completions () {
	[[ $# != 0 ]] || return
	local module="$1"
	shift
	[[ $# != 0 ]] || $module-commands
	local command="$1"
	shift

	[[ -n "$command" ]] || fin

	command_path="$(command -v "$module-$command")"
	if grep -qiE "^# completions" "$command_path"; then
		exec "$command_path" --completions "$@"
	fi
}

# print_commans <module>
print_commands () {
	IFS=: paths=($PATH)

	shopt -s nullglob

	[[ $# == 1 ]] || die "print_commands: bad arguments"

	{
		for path in "${paths[@]}"; do
			if grep -q "relax" <<< $path; then
				local prefix
				if [[ $1 = relax ]]; then
					prefix="$path/$1-"
				else
					prefix="$path/$1/$1-"
				fi
				for command in "$prefix"*; do
					command="${command##*$1-}"
					echo $command
				done
				break
			fi
		done
	} | grep -v "completions" | sort -u
}


compare_versions()
{
    local v1=( $(echo "$1" | tr '.' ' ') )
    local v2=( $(echo "$2" | tr '.' ' ') )
    local v1len="${#v1[*]}"
    local v2len="${#v2[*]}"
    local len="$(( $v1len > $v2len ? $v1len : $v2len ))"
    for ((i=0; i<len; i++))
    do
        [ "${v1[i]:-0}" -gt "${v2[i]:-0}" ] && echo -n 1 && return 0
        [ "${v1[i]:-0}" -lt "${v2[i]:-0}" ] && echo -n -1 && return 0
    done
    echo -n 0
    return 0
}

check_toolchain () {
	which xcodebuild > /dev/null || die "Not found xcodebuild"
	which /usr/libexec/PlistBuddy > /dev/null || die "Not found /usr/libexec/PlistBuddy"
	which plutil > /dev/null || die "Not found plutil"
	which codesign > /dev/null || die "Not found codesign"
	which security > /dev/null || die "Not found security"
}

pop_all() {
	local arr=($(dirs))
	local pc=${#arr[@]}
	if test $pc -gt 1;
	then
		for i in $(seq $(( $pc - 1)));
		do
			popd > /dev/null;
		done
	fi
}

TRAP() {
	local cmd=$1
	trap "${cmd}" EXIT
	trap "${cmd} die \"Interrupted\"" INT HUP
	trap "${cmd} die \"Aborted \"" ABRT
	trap "${cmd} die \"Terminate\"" TERM
}
	

make_temp () {
	if ! test -d "$REL_TEMP_ROOT"; then
		mkdir -p $REL_TEMP_ROOT
	fi
	REL_TEMP_DIR=$(mktemp -d $REL_TEMP_ROOT/XXXXXX)
	export REL_TEMP_DIR
}

clean_temp () {
	#echo "Remove Temp files. $REL_TEMP_DIR"
	if [[ ! -z $REL_TEMP_DIR ]] && [[ -d $REL_TEMP_DIR ]]; then
		rm -rf $REL_TEMP_DIR
	fi
}

teardown () {
	pop_all
	if [ -f $REL_CONFIG ]; then
		find $HERE -name "*.$BAK_EXT" |\
		while IFS= read bak
		do
			cp "$bak" "${bak%.$BAK_EXT}"
			rm "$bak"
		done
	fi
}

fin () {
	if [ $# -gt 0 ]; then
		echo -e "$@"
	fi
	exit 0
}

die () {
	if [[ -p /dev/stdin ]]; then
		die_with_status 1 "$(</dev/stdin)"
	else
		die_with_status 1 "$@"
	fi
}

die_with_status () {
	status=$1
	shift

	if test $# = 1 && test "$1" = "Interrupted"; then
		printf >&2 "$*\n"
		echo -e "${RED}Cancelled${NC}"
		exit "$status"
	fi

	printf >&2 "$ERR $*\n"
	echo -e "${RED}Failed${NC}"
	exit "$status"
}

###############
### Logger  ###
###############

__log () {
	if [[ $# != 0 ]]; then
		echo -e "$@${NC}"
	else
		if [[ -p /dev/stdin ]]; then
			echo -e "$(</dev/stdin)${NC}"
		fi
	fi
}

logv () {
	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_VERBOSE".* ]]; then
		__log "$@"
	fi
}


logd () {
	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_DEBUG".* ]]; then
		__log "$@"
	fi
}

logi () {
	__log "$@"
}


declare -x -f print_commands print_completions
declare -x -f check_toolchain compare_versions 
declare -x -f fin die die_with_status
declare -x -f logi logv logd __log
declare -x -f make_temp clean_temp 
declare -x -f teardown pop_all TRAP
