#!/bin/bash -eu
# @(#) relax: completions helpers

# print_module_completions <module> <command>
print_module_completions () {
	local _module _command _command_path

	[[ $# != 0 ]] || return
	_module="$1"
	shift

	[[ $# != 0 ]] || return
	_command="$1"
	shift

	[[ -n "$_command" ]] || return

	_command_path="$(command -v "$_module-$_command")"

	[[ -f "$_command_path" ]] || return

	if [[ $_command == "commands" ]]; then
		exec $_command_path
	elif grep -q "^# completions" "$_command_path"; then
		exec "$_command_path" --completions "$@"
	fi
}

# print_commans <module>
print_commands () {
	IFS=: paths=($PATH)

	shopt -s nullglob

	[[ $# == 1 ]] || die "print_commands: bad arguments"

	{
		for path in "${paths[@]}"; do
			if grep -q "relax" <<< $path; then
				local prefix="$path/$1-"
				for command in "$prefix"*; do
					command="${command##*$1-}"
					echo $command
				done
				break
			fi
		done
	} | grep -v "completions" | sort -u
}


declare -x -f print_commands print_module_completions
