#!/usr/bin/env bash -eu
# @(#) relax: utility functions

#################
###  Defines  ###
#################

export REL_TEMP_DIR=
export REL_LOG_LEVEL=
export REL_LOG_LEVEL_DEBUG=DEBUG
export REL_LOG_LEVEL_VERBOSE=VERBOSE
export ARROW="${BLUE}==>${NC}${BOLD}"
export ERR=${RED}Error:${NC}
export WARN=${YELLOW}Warning:${NC}
export NOTE=${BOLD}Note:${NC}

#################
### Functions ###
#################


progress_bar()
{
	local pid=$1
	local delay=0.75
	while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
		printf  "▓"
		sleep $delay
	done
}

check_toolchain () {
	which xcodebuild > /dev/null || die "Not found xcodebuild"
	which /usr/libexec/PlistBuddy > /dev/null || die "Not found /usr/libexec/PlistBuddy"
	which plutil > /dev/null || die "Not found plutil"
	which codesign > /dev/null || die "Not found codesign"
}

pop_all() {
	local arr=($(dirs))
	local pc=${#arr[@]}
	if test $pc -gt 1;
	then
		for i in $(seq $(( $pc - 1)));
		do
			popd > /dev/null;
		done
	fi
}

TRAP() {
	local cmd=$1
	trap "${cmd}" EXIT
	trap "${cmd} die \"Interrupted\"" INT
	trap "${cmd} die \"Terminate\"" TERM
}
	

make_temp () {
	if ! test -d "$REL_TEMP_ROOT"; then
		mkdir -p $REL_TEMP_ROOT
	fi
	REL_TEMP_DIR=$(mktemp -d $REL_TEMP_ROOT/XXXXXX)
	export REL_TEMP_DIR
}

clean_temp () {
	#echo "Remove Temp files. $REL_TEMP_DIR"
	if [[ ! -z $REL_TEMP_DIR ]] && [[ -d $REL_TEMP_DIR ]]; then
		rm -rf $REL_TEMP_DIR
	fi
}

teardown () {
	pop_all
	if [ -f $REL_CONFIG ]; then
		find $HERE -name "*.$BAK_EXT" |\
		while IFS= read bak
		do
			cp "$bak" "${bak%.$BAK_EXT}"
			rm "$bak"
		done
	fi
}

fin () {
	if [ $# -gt 0 ]; then
		echo -e "$@"
	fi
	exit 0
}

die () {
	die_with_status 1 "$@"
}

die_with_status () {
	status=$1
	shift

	if test $# = 1 && test "$1" = "Interrupted"; then
		printf >&2 "$*\n"
		echo -e "${RED}Cancelled${NC}"
		exit "$status"
	fi

	printf >&2 "$ERR $*\n"
	echo -e "${RED}Failed${NC}"
	exit "$status"
}

###############
### Logger  ###
###############

__log () {
	if [[ $# != 0 ]]; then
		echo -e "$@${NC}"
	else
		if [[ -p /dev/stdin ]]; then
			cat -
		fi
	fi
}

logv () {
	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_VERBOSE".* ]]; then
		__log "$@"
	fi
}


logd () {
	if [[ ${REL_LOG_LEVEL:-undefined} =~ .*"$REL_LOG_LEVEL_DEBUG".* ]]; then
		__log "$@"
	fi
}

logi () {
	__log "$@"
}

declare -x -f check_toolchain progress_bar
declare -x -f fin die die_with_status
declare -x -f logi logv logd __log
declare -x -f make_temp pop_all clean_temp TRAP
