#!/usr/bin/env bash -eu
# @(#) relax `keychain-create` command
# completions

usage () {
	cat <<-EOM
	usage: ${ME} keychain create <keychain> -p <keychain-pass>

	EOM
	fin
}


create_keychain () {
	local keychain keychain_pass
	while [ $# -ne 0 ];
	do
		arg=$1
		shift
		case $arg in
		-p)
			keychain_pass=$1
			shift
			;;
		*)
			keychain=$arg
			;;
		esac
	done

	[[ -n $keychain ]] || usage;
	[[ -n $keychain_pass ]] || usage;

	if is_exist_keychain $keychain; then
		fin "Already exist keychain: $keychain."
	fi

	$SECURITY create-keychain -p $keychain_pass $keychain
	$SECURITY set-keychain-settings -t 3600 $keychain
	logi "Created: $keychain"
}

[[ $# != 0 ]] || usage

arg=$1
case $arg in
-h|--help) usage ;;
--completions)
	shift
	while [[ $# != 0 ]]; 
	do
		case $1 in
			-) fin "-p" ;;
		esac
		shift
	done
	fin
	;;
esac

create_keychain "$@"
