#!/bin/bash -eu

usage () {
	cat <<-EOM
	Usage: ${ME} keychain <command> ...

	Commands:
	    add		Add identities in a pkcs12 file
	    certs	List identities(pairs of certificate and private key)
	    create	Create a keychain
	    delete	Delete a keychain
	    info	Print hashs and common names of identities in a pkcs12 file
	    ls		List keychains
	    reset	Reset the default keychain to login.keychain
	    rm		Remove an identity with the hash
	    use		Set up a keychain to use it
	EOM
	fin
}


if [ $# = 0 ]; then
	usage
	fin
fi

command=$1
shift
case $command in 
help)
	if [ $# == 0 ]
	then
		usage
	else 
		command=$1
		shift
		command_path="$(command -v "relax-$command" || true)"
		if ! [ -n "$command_path" ]; then
			die "No such command \`$command'"
		fi

		bash -f "$command_path" -h
		fin
	fi
	;;
"")
	usage
	fin
	;;
* )
	module_path=${0%/*}
	module=${module_path##*/}
	command_path="$(command -v "${module}-${command}" || true)"
	if ! [ -n "$command_path" ]; then
		die "No such $module command \`$command'"
	fi
	
	TRAP "clean_temp;"
	make_temp

	"$command_path" "$@"
	;;	
esac
