#!/usr/bin/env bash -eu
# @(#) relax `keychain-reset` command

usage () {
	cat <<-EOM
	usage: ${ME} keychain reset

	EOM
	fin
}

reset_keychain () {
	reset_default_keychain login.keychain
	logi "Reset the default keychain to login.keychain "
}

if [[ $# != 0 ]]; then
	case $1 in
	-h|--help|*) usage ;;
	esac
else
	reset_keychain
fi


