#!/usr/bin/env bash -eu
# @(#) relax `keychain-reset` command
# completions

usage () {
	cat <<-EOM
	usage: ${ME} keychain reset

	EOM
	fin
}

reset_keychain () {
	logi "Reset the default keychain to login.keychain "
	reset_default_keychain login.keychain
}

if [[ $# != 0 ]]; then
	case $1 in
	--completions) 
		fin
		;;
	-h|--help|*) usage ;;
	esac
else
	reset_keychain
fi


