name: ci

on:
  pull_request:
    branches:
    - master

jobs:
  test_go:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version:  '1.11'
    - name: Test go packages
      run: make test-go
      env:
        CERTS_PASS: ${{ secrets.CERTS_PASS }}
        DECORD_KEY: ${{ secrets.DECORD_KEY }}

  xcode10_3:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Testing on Xcode 10.3"
      run: test/travis_ci.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_10.3.app
        CERTS_PASS: ${{ secrets.CERTS_PASS }}
        DECORD_KEY: ${{ secrets.DECORD_KEY }}

  xcode11_7:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Testing on Xcode 11.7"
      run: test/travis_ci.sh
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.7.app
        CERTS_PASS: ${{ secrets.CERTS_PASS }}
        DECORD_KEY: ${{ secrets.DECORD_KEY }}

#  xcode12_3:
#    runs-on: macOS-latest
#    steps:
#    - uses: actions/checkout@v1
#     - name: "Testing on Xcode 12.3"
#      run: test/travis_ci.sh
#      env:
#        DEVELOPER_DIR: /Applications/Xcode_12.3.app
#        CERTS_PASS: ${{ secrets.CERTS_PASS }}
#        DECORD_KEY: ${{ secrets.DECORD_KEY }}
#
